# Generated by Django 4.2.2 on 2023-07-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_searchresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresults',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
    ]
