# Generated by Django 4.2.2 on 2023-07-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_searchresults_item_id'),
    ]

    operations = [
    ]
